---
  extends:
    - 'airbnb-base'
    - 'plugin:jest/recommended'
    - 'plugin:lodash-fp/recommended'

  parser: babel-eslint

  plugins:
  - jest
  - babel

  env:
    node: true
    jest: true

  rules:
    no-console: 0
